name: teamtodo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^7.2.0
  shared_preferences: ^2.0.8
  flutter_dotenv: ^5.0.2
  retrofit: ^2.0.1
  json_annotation: ^4.1.0
  dio: ^4.0.1
  dio_http_cache: ^0.3.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^4.1.4
  build_runner:
  retrofit_generator:
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
